# -*- coding: utf-8 -*-
"""Assignment 27  Sketching.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X5Imvmy5lR1glzckQ0PFt_kFhlM1Afr5
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
import matplotlib.pyplot as plt

# %matplotlib inline


image = cv2.imread("photo.jpeg")

y1 = cv2.imread("photo.jpeg",0)
# plt.imshow(y1 , cmap = "gray")
# y1 = cv2.cvtColor(y1, cv2.COLOR_BGR2RGB)
# plt.imshow(y1)

a = np.copy(y1)

b = cv2.Canny(a, 8, 10)

plt.imshow(b  , cmap='gray' )